-- user
DROP TABLE IF EXISTS user;

CREATE TABLE user
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	age INT(11) NULL DEFAULT NULL COMMENT '年龄',
	title VARCHAR(50) NULL DEFAULT NULL COMMENT '称号',
	PRIMARY KEY (id)
);
-- role
DROP TABLE IF EXISTS role;

CREATE TABLE role
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '角色名',
	`order` INT(11) NULL DEFAULT NULL COMMENT '排序',
	PRIMARY KEY (id)
);
-- user role
DROP TABLE IF EXISTS user_role;

CREATE TABLE user_role
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	userId BIGINT(20) NULL DEFAULT NULL COMMENT '用户Id',
	roleId BIGINT(20) NULL DEFAULT NULL COMMENT '角色Id',
	PRIMARY KEY (id)
);